### ISSUE TITLE
distance has no effect

### ISSUE THREAD

**Issue by zwhitchcox** [c0bra/color-scheme-js#14]
Even when taken directly from the example, distance no effect. I'm not sure what function it is supposed to serve exactly, but from what I can see it makes no difference on the color scheme at all, no matter what value I insert.

**Comment by c0bra** [comment]
Check the example: http://c0bra.github.io/color-scheme-js/

It has no effect on mono or contrast schemes

**Comment by c0bra** [comment]
Going to close since there's been no reply.
