### ISSUE TITLE
"TypeError: colorset1 is undefined" when using the from_hex() method

### ISSUE THREAD

**Issue by Banasura** [c0bra/color-scheme-js#5]
Hi,

I am trying to get working your amazing lib in my project, but when I try to generate colors using the from_hex() method, I get the following error in the browser: `TypeError: colorset1 is undefined (color-scheme.js:522:10)`

I noticed that if I replaced `from_hex()` by the `from_hue()` method, it was working, so it sounds like a bug, that's why I'm posting it here.

In the debugger, at line 511, there is `colorset1 = ColorScheme.COLOR_WHEEL[derivative1];`, but `derivative1` is set to -15, so that's why `colorset1` is undefined... Have you any idea of the source of the problem?

Here is a sample of the code I used:

```js
var theme = this.colorScheme.from_hex("AD1457")
                            .scheme('contrast')
                            .variation('light');
```

**UPDATE**: I just noticed that the problem occurs in the demo too when I try to put "AD1457" in the Hex field of [http://c0bra.github.io/color-scheme-js/](http://c0bra.github.io/color-scheme-js/).

Thank you in advance & keep up the good work!

**Comment by c0bra** [comment]
@Banasura thanks for the heads-up.

Looks like the hues weren't being allowed to go around the color wheel. Somehow your hex color was ending up with a negative hue: -26, and that was causing things to bomb.

I've added a change to v0.0.6 that will rotate the hues around so -26 becomes 334. Let me know if you have any issues with the change!
