### ISSUE TITLE
register at bower.io

### ISSUE THREAD

**Issue by dkebler** [c0bra/color-scheme-js#7]
Mind registering your repo at bower.io as well??   Although I use npm I use bower for js frontend libraries as opposed to npm for actual node modules.

A main entry(s) in your bower.json is all that is needed.

Thx.

http://bower.io/docs/creating-packages/

**Comment by c0bra** [comment]
I don't think I'm going to do this. Anymore it's too easy to use npm for everything, or use both npm and bower regardless of which part of your app you're using them in.
