### ISSUE TITLE
Register at cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by ongle2** [c0bra/color-scheme-js#9]
Would you consider registering at cdnjs? It can be done via pull request: https://github.com/cdnjs/cdnjs

**Comment by TagoDR** [comment]
I second that, please register it on cdnjs

**Comment by c0bra** [comment]
Looking into it; been a while since I put a library on it.

**Comment by c0bra** [comment]
Just waiting on the merge: https://github.com/cdnjs/cdnjs/pull/11372#pullrequestreview-42042771

**Comment by c0bra** [comment]
@TagoDR @ongle2 https://cdnjs.com/libraries/color-scheme
